# CI build definition for https://ci.appveyor.com/project/olegsych/simply-collections
# To learn more, see http://www.appveyor.com/docs/appveyor-yml

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2017

build_script:
- nuget restore
- msbuild simply.collections.sln /m /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild simply.collections.sln /m /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- vstest.console bin\Win32\test.dll /Platform:x86 /logger:Appveyor
- vstest.console bin\x64\test.dll /Platform:x64 /logger:Appveyor /inIsolation

after_test:
- nuget pack "src\simply.collections.nuspec" -BasePath "src" -OutputDirectory "bin" -Properties "version=%appveyor_build_version%"

artifacts:
- path: bin\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 236NXQ/p6GSTraxqHTtmNVFcDJlTwDjwxzbdJIcDpk8Lu7hAkz1ThK6eqeVeTMz6
  skip_symbols: true
- provider: GitHub
  auth_token:
    secure: 0odiqbMNXJj+DNBK/pFP5to5mGxy1JfdSpA6dUA233dNgQitI78fjDm5vgmafgpR
  artifact: /.*\.nupkg/

nuget:
  project_feed: true
  account_feed: true
